name: Run Pragma Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-pragma:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test Model Import
        id: pragma
        uses: Silverlan/test_ci2/github_actions/run_tests@main  # This points to the root directory of your repository where action.yml is located
        with:
          test-scripts: |
            "tests/assets/assets.lua"
            "tests/game/game.lua"
          artifacts-name: "assets"
          screenshot: true

      #- name: Launch PFM
      #  id: launch-pfm
      #  uses: Silverlan/test_ci2/github_actions/test@main  # This points to the root directory of your repository where action.yml is located
      #  with:
      #    lua-script: tests/pfm/launch_pfm.lua
      #    artifacts-name: "launch-pfm"
      #    screenshot: true

      #- name: Output Result
      #  shell: bash
      #  if: always()
      #  run: |
      #    echo "Exit-code: ${{ steps.pragma.outputs.exit-code }}"
      #    echo "Error: ${{ steps.pragma.outputs.error }}"
      #    echo "Lua-error: ${{ steps.pragma.outputs.lua-error }}"
